1 - Bibliotecas

In [21]:
import pandas as pd
import openpyxl
import os

2 - Lendo arquivo dim_funcionário.parquet

In [22]:
input_path = "../Data/2 - Bronze/dim_escala.parquet"
output_path = "../Data/3 - Silver"


df = pd.read_parquet(input_path)

df

   Cód Escala                         Escala
0           1  08-18 seg-qui / 08-17 sex ADM
1          13  07-17 seg-qui / 07-16 sex COP
2          14  08-18 seg-qui / 08-17 sex PRO
3           5      14-21 e 06-14 seg-sáb PRO
4          15  06-12/12-18/22-05 seg-sáb PRO
5          41        06-12/12-18/22-05/22-05
6          37      08-16/22-05 seg-sáb manut
7          22  06-12/12-18/22-05 REV 6x2 PRO
8          29            09-17/22-05 seg-sáb
9          17  06-13/14-21/22-05 REV 6x2 PRO
10         19  12-18/06-12/22-05 seg-sáb PRO
11         21  12-18/06-12/22-05 REV 6x2 PRO
12         25       14:00 as 22:00 SEG a SEX
13         30              08-16 seg-sáb PRO
14         42          06 AS 12/22-05/12AS18
15         16  06-13/14-21/22-05 seg-sáb PRO
16         33    12:00 as 20:00 - int.1h exp
17          8              08-15 seg-sex EST
18          9              10-17 seg-sex EST
19         10  11-18 seg-qui / 10-17 sex EST
20         12      13:00-17:00 s-sx APRENDIZ
21         18      08:00 - 12:00 seg-sex APR
22         38    14:00 as 18:00 aprendizagem
23         26        06-13/14-21 seg-sáb PRO
24          6        06-13/14-21 seg-sáb PRO
25         35    08:00 as 15:00 - int.1h exp
26          4              22-05 seg-sex PRO

3 - Renomando Colunas

In [23]:
df = df.rename(columns={'Cód Escala': 'cod_escala', 
                        'Escala': 'escala',})

4 - Tipando as colunas do data frame

In [24]:
tipos = { 
    'cod_escala': 'Int64',
    'escala': 'string',
}

df = df.astype(tipos)

5 - Garantindo que os IDs das escalas sempre sejam numéricos

In [25]:
df['cod_escala'] = pd.to_numeric(df['cod_escala'], errors='coerce')

6 - Padronizando os dados do tipo string para maiúsculo

In [26]:
colunas_texto = df.select_dtypes(include=['string']).columns

for col in colunas_texto:
    df[col] = df[col].str.upper().str.strip()

df

    cod_escala                         escala
0            1  08-18 SEG-QUI / 08-17 SEX ADM
1           13  07-17 SEG-QUI / 07-16 SEX COP
2           14  08-18 SEG-QUI / 08-17 SEX PRO
3            5      14-21 E 06-14 SEG-SÁB PRO
4           15  06-12/12-18/22-05 SEG-SÁB PRO
5           41        06-12/12-18/22-05/22-05
6           37      08-16/22-05 SEG-SÁB MANUT
7           22  06-12/12-18/22-05 REV 6X2 PRO
8           29            09-17/22-05 SEG-SÁB
9           17  06-13/14-21/22-05 REV 6X2 PRO
10          19  12-18/06-12/22-05 SEG-SÁB PRO
11          21  12-18/06-12/22-05 REV 6X2 PRO
12          25       14:00 AS 22:00 SEG A SEX
13          30              08-16 SEG-SÁB PRO
14          42          06 AS 12/22-05/12AS18
15          16  06-13/14-21/22-05 SEG-SÁB PRO
16          33    12:00 AS 20:00 - INT.1H EXP
17           8              08-15 SEG-SEX EST
18           9              10-17 SEG-SEX EST
19          10  11-18 SEG-QUI / 10-17 SEX EST
20          12      13:00-17:00 S-SX APRENDIZ
21          18      08:00 - 12:00 SEG-SEX APR
22          38    14:00 AS 18:00 APRENDIZAGEM
23          26        06-13/14-21 SEG-SÁB PRO
24           6        06-13/14-21 SEG-SÁB PRO
25          35    08:00 AS 15:00 - INT.1H EXP
26           4              22-05 SEG-SEX PRO

7 - Enviando dim_escala tratada para a camada silver

In [27]:
df.to_parquet(os.path.join(output_path, "dim_escala.parquet"), index=False)