1 - Bibliotecas

In [64]:
import pandas as pd
import openpyxl
import os

2 - Lendo arquivo fato_ficha_financeira

In [65]:
input_path = "../Data/2 - Bronze/fato_ficha_financeira.parquet"
output_path = "../Data/3 - Silver"


df = pd.read_parquet(input_path)

df

,Matricula,Cargo,Mês Pag.,Evento,Descrição,Tipo,Valor
0,1182.0,VENDEDOR INTERNACIONAL,fev/20,1.0,Horas Normais,Provento,"4.588,62"
1,1182.0,VENDEDOR INTERNACIONAL,fev/20,5.0,Horas Férias Diurnas,Provento,"1.147,15"
2,1182.0,VENDEDOR INTERNACIONAL,fev/20,226.0,Subs.Emp.Unimed Est. Enf.,Outros,"312,7"
3,1182.0,VENDEDOR INTERNACIONAL,fev/20,233.0,Desc.Copart. Unimed,Desconto,"14,1"
4,1182.0,VENDEDOR INTERNACIONAL,fev/20,249.0,Subs. Empresa Alimentação,Outros,300
...,...,...,...,...,...,...,...
28725,NaN,NaN,NaN,NaN,Provisão 13º Saldo Transf.,NaN,0
28726,NaN,NaN,NaN,NaN,GPS Parte Empresa,NaN,"194.601,70"
28727,NaN,NaN,NaN,NaN,GPS Terceiros,NaN,"34.600,38"
28728,NaN,NaN,NaN,NaN,GPS Acid. Trabalho,NaN,"26.793,72"
28729,NaN,NaN,NaN,NaN,GPS Convênios,NaN,"9.671,47"

3 - Renomeando colunas

In [66]:
df = df.rename(columns={'Matricula': 'cod_funcionario', 
                        'Cargo': 'cargo',
                        'Mês Pag.': 'mes_pagamento',
                        'Evento': 'evento',
                        'Descrição': 'descricao',
                        'Tipo': 'tipo',
                        'Valor': 'valor',
                        })

4 - Excluindo linhas de resumo (em branco) do data frame

In [67]:
df.dropna(how='any', inplace=True)
 
df

,cod_funcionario,cargo,mes_pagamento,evento,descricao,tipo,valor
0,1182.0,VENDEDOR INTERNACIONAL,fev/20,1.0,Horas Normais,Provento,"4.588,62"
1,1182.0,VENDEDOR INTERNACIONAL,fev/20,5.0,Horas Férias Diurnas,Provento,"1.147,15"
2,1182.0,VENDEDOR INTERNACIONAL,fev/20,226.0,Subs.Emp.Unimed Est. Enf.,Outros,"312,7"
3,1182.0,VENDEDOR INTERNACIONAL,fev/20,233.0,Desc.Copart. Unimed,Desconto,"14,1"
4,1182.0,VENDEDOR INTERNACIONAL,fev/20,249.0,Subs. Empresa Alimentação,Outros,300
...,...,...,...,...,...,...,...
28609,1745.0,CONTROLADOR DE ESTOQUE I,jul/20,2453.0,Vale Transporte,Desconto,102
28610,1745.0,CONTROLADOR DE ESTOQUE I,jul/20,2470.0,Desconto Alimentação,Desconto,"1,5"
28611,1745.0,CONTROLADOR DE ESTOQUE I,jul/20,2478.0,Desconto Refeição,Desconto,"2,5"
28612,1745.0,CONTROLADOR DE ESTOQUE I,jul/20,2500.0,FGTS,Outros,"215,52"
28613,1745.0,CONTROLADOR DE ESTOQUE I,jul/20,2519.0,Diferenças SEFIP,Outros,"0,01"

5 - Tipando colunas do data frame

In [68]:
tipos = { 
    'cod_funcionario': 'Int64',
    'cargo': 'string',
    'mes_pagamento': 'string',
    'evento': 'int64',
    'descricao': 'string',
    'tipo': 'string',
    'valor': 'float',
}

df

,cod_funcionario,cargo,mes_pagamento,evento,descricao,tipo,valor
0,1182.0,VENDEDOR INTERNACIONAL,fev/20,1.0,Horas Normais,Provento,"4.588,62"
1,1182.0,VENDEDOR INTERNACIONAL,fev/20,5.0,Horas Férias Diurnas,Provento,"1.147,15"
2,1182.0,VENDEDOR INTERNACIONAL,fev/20,226.0,Subs.Emp.Unimed Est. Enf.,Outros,"312,7"
3,1182.0,VENDEDOR INTERNACIONAL,fev/20,233.0,Desc.Copart. Unimed,Desconto,"14,1"
4,1182.0,VENDEDOR INTERNACIONAL,fev/20,249.0,Subs. Empresa Alimentação,Outros,300
...,...,...,...,...,...,...,...
28609,1745.0,CONTROLADOR DE ESTOQUE I,jul/20,2453.0,Vale Transporte,Desconto,102
28610,1745.0,CONTROLADOR DE ESTOQUE I,jul/20,2470.0,Desconto Alimentação,Desconto,"1,5"
28611,1745.0,CONTROLADOR DE ESTOQUE I,jul/20,2478.0,Desconto Refeição,Desconto,"2,5"
28612,1745.0,CONTROLADOR DE ESTOQUE I,jul/20,2500.0,FGTS,Outros,"215,52"
28613,1745.0,CONTROLADOR DE ESTOQUE I,jul/20,2519.0,Diferenças SEFIP,Outros,"0,01"

6 - Garantir que os IDs dos funcionarios sempre sejam numéricos

In [69]:
df['cod_funcionario'] = pd.to_numeric(df['cod_funcionario'], errors='coerce')

7 - Padronizando os dados do tipo string para maísculo

In [70]:
colunas_texto = df.select_dtypes(include=['string']).columns

for col in colunas_texto:
    df[col] = df[col].str.upper().str.strip()

df

,cod_funcionario,cargo,mes_pagamento,evento,descricao,tipo,valor
0,1182.0,VENDEDOR INTERNACIONAL,FEV/20,1.0,HORAS NORMAIS,PROVENTO,"4.588,62"
1,1182.0,VENDEDOR INTERNACIONAL,FEV/20,5.0,HORAS FÉRIAS DIURNAS,PROVENTO,"1.147,15"
2,1182.0,VENDEDOR INTERNACIONAL,FEV/20,226.0,SUBS.EMP.UNIMED EST. ENF.,OUTROS,"312,7"
3,1182.0,VENDEDOR INTERNACIONAL,FEV/20,233.0,DESC.COPART. UNIMED,DESCONTO,"14,1"
4,1182.0,VENDEDOR INTERNACIONAL,FEV/20,249.0,SUBS. EMPRESA ALIMENTAÇÃO,OUTROS,300
...,...,...,...,...,...,...,...
28609,1745.0,CONTROLADOR DE ESTOQUE I,JUL/20,2453.0,VALE TRANSPORTE,DESCONTO,102
28610,1745.0,CONTROLADOR DE ESTOQUE I,JUL/20,2470.0,DESCONTO ALIMENTAÇÃO,DESCONTO,"1,5"
28611,1745.0,CONTROLADOR DE ESTOQUE I,JUL/20,2478.0,DESCONTO REFEIÇÃO,DESCONTO,"2,5"
28612,1745.0,CONTROLADOR DE ESTOQUE I,JUL/20,2500.0,FGTS,OUTROS,"215,52"
28613,1745.0,CONTROLADOR DE ESTOQUE I,JUL/20,2519.0,DIFERENÇAS SEFIP,OUTROS,"0,01"

8 - Enviando fato_ficha_financeira tratada para a camada silver

In [71]:
df.to_parquet(os.path.join(output_path, "fato_ficha_financeira.parquet"), index=False)