1 - Bibliotecas

In [8]:
import pandas as pd
import openpyxl
import os

2 - Lendo arquivo dim_cargo.parquet

In [9]:
input_path = "../Data/2 - Bronze/dim_cargo.parquet"
output_path = "../Data/3 - Silver"


df = pd.read_parquet(input_path)

df

    Cód Cargo                           Cargo
0         249  AUXILIAR DE SERVIÇOS DE GERAIS
1         260              CONTROLER EM GERAL
2      001001                   DIRETOR GERAL
3         159               VENDEDOR EM GERAL
4         307    SUPERVISOR COMPRAS DE BLOCOS
..        ...                             ...
246       091  SUPERVISOR MARKETING COMERCIAL
247       084    RESPONSAVEL PROCESSO ARMAZEM
248    062001     GERENTE DE RECURSOS HUMANOS
249    037001  AUXILIAR LINHA DE PRODUÇÃO DES
250       090  SUPERVISOR COMPRAS ALMOXARIFAD

[251 rows x 2 columns]

3 - Renomeando colunas

In [10]:
df = df.rename(columns={'Cód Cargo': 'cod_cargo', 
                        'Cargo': 'cargo',
                      })

4 - Tipando as colunas do data frame

In [11]:
tipos = { 
    'cod_cargo': 'Int64',
    'cargo': 'string',

}

df = df.astype(tipos)

5 - Garantir que os IDs dos cargos sempre sejam numéricos

In [12]:
df['cod_cargo'] = pd.to_numeric(df['cod_cargo'], errors='coerce')

6 - Padronizando os dados do tipo string para maiúsculo

In [13]:
colunas_texto = df.select_dtypes(include=['string']).columns

for col in colunas_texto:
    df[col] = df[col].str.upper().str.strip()

df

     cod_cargo                           cargo
0          249  AUXILIAR DE SERVIÇOS DE GERAIS
1          260              CONTROLER EM GERAL
2         1001                   DIRETOR GERAL
3          159               VENDEDOR EM GERAL
4          307    SUPERVISOR COMPRAS DE BLOCOS
..         ...                             ...
246         91  SUPERVISOR MARKETING COMERCIAL
247         84    RESPONSAVEL PROCESSO ARMAZEM
248      62001     GERENTE DE RECURSOS HUMANOS
249      37001  AUXILIAR LINHA DE PRODUÇÃO DES
250         90  SUPERVISOR COMPRAS ALMOXARIFAD

[251 rows x 2 columns]

7 - Enviando dim_cargo para a camada silver

In [14]:
df.to_parquet(os.path.join(output_path, "dim_cargo.parquet"), index=False)